language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
cache: bundler
before_install:
  - # we want bundler 1.7 (for now) https://docs.travis-ci.com/user/languages/ruby/
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script: bundle install && bundle exec rspec spec/
